### PR TITLE
Ensure that jQuery is always installed

### PR DESCRIPTION
**Pull request by saimn**
jQuery is not longer installed by default with Sphinx 6.0

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
@saimn - I wonder why the test action is chosen not to run on PRs?

**Comment by saimn** [comment]
@bsipocz - good catch, the workflow was disabled ;)

**Comment by saimn** [comment]
A lot of things are obsolete with this package though, not sure testing Sphinx 1.7 is useful nowadays ...

**Comment by saimn** [comment]
Will do a release soon to fix the docs build for astropy v5.2.2

**Comment by bsipocz** [comment]
> not sure testing Sphinx 1.7 is useful nowadays ...

lol, probably not.

**Pull request merged**
