### PR TITLE
Replace numpydoc with napoleon

### LINKED ISSUE #5: Consider using sphinx.ext.napoleon instead of numpydoc
As originally mentioned in https://github.com/astropy/astropy-helpers/issues/270, we should explore whether to switch from numpydoc to sphinx.ext.napoleon. The main benefit would be to reduce the number of dependencies (we could remove numpydoc).

Packages can easily try out ``sphinx.ext.napoleon`` if they are using sphinx-astropy as they just need to do something like the following in their ``conf.py``:

```
extensions.remove('numpydoc')
extensions.append('sphinx.ext.napoleon')
```

and presumably add a bunch of configuration for sphinx.ext.napoleon. If anyone fancies trying to do something like this with astropy core for example, feel free to.

If we decide to do this in the default config here, we should determine whether it will have a big impact on downstream packages, and if so we may have to make a new version of ``conf.py`` (``v2``).

### PR DESCRIPTION
**Pull request by pllim**
Fix #5

### CODE REVIEW

**Comment by pllim** [comment]
I tried using `napoleon` for astropy/astropy#10524 and got *a lot* of warnings. Obviosly, it has a different standard from `numpydoc`. 😱

**Comment by astrofrog** [comment]
Indeed, it breaks so many things that we would need to make this a v2 config even if we fix the warnings over at astropy. I had to open some issues over at Sphinx as there are some real bugs in Napoleon, will xref later.

**Comment by saimn** [comment]
Numpydoc is used by Numpy, Scipy, Matplotlib and probably many others, and is now well maintained (this was more a problem a few years ago), so what would be the gain of switching to napoleon which is less widely used and tested ?

**Comment by pllim** [comment]
I haven't been following the Sphinx dev world. I thought `napoleon` is the canon one since it is [shipped by Sphinx itself](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) and hence reduce our dependency by one package. But I am okay if we decide to stick with it too. I completely forgot about this until numpy/numpydoc#275 cropped up.

**Comment by astrofrog** [comment]
To some extent the canon one is numpydoc since they defined the docstring format - I agree it would be nice if we could reduce the number of dependencies but I think Napoleon isn’t quite there yet.

**Comment by pllim** [comment]
> Napoleon isn’t quite there yet

Even after all these years... Color me surprised!

**Comment by pllim** [comment]
(Feel free to close then if you think this is irrelevant.)

**Comment by astrofrog** [comment]
I think we should close this for now until it works in astropy core (which will be a lot of work), but re-open if you disagree!

**Pull request closed without merging**
