### PR TITLE
Add sphinx_astropy.ext.example extension for building an example gallery

### PR DESCRIPTION
**Pull request by jonathansick**
This PR implements a functional example gallery Sphinx extension, as initially described in astropy/astropy#7242 — this PR supersedes #22.

The premise is that documentation pages potentially contain many useful snippets of content that are useful in their own right, outside the context of the page where they are originally written. These snippets can be examples, how-tos, and so on. This Sphinx extension provides a way of surfacing these pieces of content into a centralized gallery.

From a documentation author's perspective, the main API is the example directive, which demarks example content:

```rst
.. example:: Title of the example
   :tags: first-tag, another-tag

   Content of the example.

   More content in the example.

This content is not part of the example.
```

The example directive does not change the visual appearance of the example content in the documentation text.

During the Sphinx build, though, that content is copied into a new, auto-generated page at `/examples/title-of-the-example.html`. There is an index page that lists all examples at `/examples/index.html`. There are also pages for each tag that list examples with the associated tag: `examples/tags/first-tag.html` and `examples/tags/another-tag.html`

## Demo

This is a demo of an example gallery generated from examples identified in the `astropy.io` and `astropy.nddata` packages.

http://astropy-example.jsick.codes.s3-website-us-east-1.amazonaws.com/examples/index.html

## Configurability

There are three configuration variables:

- `astropy_examples_enabled`. If `True`, the example gallery (i.e., pages in `/examples/`) are generated. **This defaults to `False`** so that projects can begin using the example directive, but not need to change the appearance of the build documentation. This provides a means of incremental adoption.

- `astropy_examples_dir`. The directory where the example gallery is published. The default is `examples`.

- `astropy_examples_h1`. Configures the character to use for "h1" headlines in reStructuredText. Defaults to `#`.

## Processing overview

During the `builder-inited` phase, the `preprocess_examples` function scans every doc in the Sphinx source tree to find `example` directives. This function generates a standalone reStructuredText page for each example, a page for each tag, and the main index page. By creating these pages in the `builder-inited` phase, they can be parsed later on during the regular build.

When the `example` directive is handled, the directive passes the content through, but wrapped in a custom `ExampleMarkerNode`. In HTML, this node becomes a `<div>` with class `astropy-example-source` and an `id` attribute that identifies the example.

The standalone example pages are templated to include a `example-content` directive. These directives add a ``<div>`` to the HTML page with a class of `astropy-example-content` and an `id` attribute that identifies the example that belongs.

The `builder-finished` phase is when the example content is copied onto the standalone example pages. Using BeautifulSoup4, the extension copies content within `div.astropy-example-source` tags and then replaces the `div.astropy.example-content` tags with that content.

## Next steps

Beyond this PR, the next steps for this extension are:

- Create a more sophisticated browsing interface on the example gallery's landing pages. We want a card layout with a thumbnail image and teaser text for each example.

- Publish data about the standalone examples so that they can be listed from learn.astropy.org.

- Better support for incremental Sphinx builds. Right now, the extension clears out the example directory on each build, but a more selective approach to rebuilds can be taken.

### CODE REVIEW

**Comment by jonathansick** [comment]
@astrofrog do you want to review this as-is, or should I first transplant this into a standalone Python package and separate GitHub repo?

I was thinking about what the package should be named, in that case. PyPI `sphinx-examples` is available. I was also thinking about the comment from the coord meeting that we aren't necessarily building an "example gallery" (assuming that a gallery implies images/plots). Can we incorporate some terminology into the name that reflects its nature of transplanting existing content? Maybe `sphinx-highlights`? What do you think @kelle ?

**Comment by jonathansick** [comment]
I remember that "example library" was an emerging consensus from the Coord meeting. `sphinx-example-library` could be the PyPI package?

**Comment by bsipocz** [comment]
I rather like the mix of the two from above `sphinx-example-highlights`. calling it `library` is a bit overloads the word with normal life meaning, and that's a bit confusing...

**Comment by astrofrog** [comment]
@jonathansick - can we close this PR now that the extension lives in https://github.com/astropy/sphinx-example-index?

**Comment by jonathansick** [comment]
Yep, moving this over to the sphinx-example-index repo right now.

**Pull request closed without merging**
